title : My Portfolio - Rizal Gibran
logo: /img/Photoroom_20250623_102218.JPEG
description: Website Portfolio of Data Science and Machine Learning
show_downloads: true
theme: jekyll-theme-minimal

# navigasi
navigation: 
  - title: Home
    url: index
  - title: Projects
    url: project
