title : My Portfolio
logo: /img/myphoto.png
#description: Website Portfolio of Data Science and Machine Learning
#show_downloads: true
theme: jekyll-theme-minimal

# navigasi
navigation: 
  - title: Home
    url: index
  - title: Projects
    url: project
